apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - external-litellm.yaml
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: litellm
      namespace: dokkaebi-llm
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: litellm-postgres
      namespace: dokkaebi-llm
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
  - target:
      version: v1
      kind: Service
      name: litellm
      namespace: dokkaebi-llm
    patch: |-
      - op: remove
        path: /spec/selector
