apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - rbac-fire.yaml
  - rbac-hammer-profiles.yaml
  - admission-policy.yaml
  - networkpolicy.yaml
