apiVersion: v1
kind: ServiceAccount
metadata:
  name: dokkaebi-fire
  namespace: dokkaebi-system
  labels:
    app.kubernetes.io/name: dokkaebi-fire
    app.kubernetes.io/part-of: dokkaebi
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hammer-no-k8s
  namespace: dokkaebi-workers
  labels:
    app.kubernetes.io/name: dokkaebi-hammer
    app.kubernetes.io/part-of: dokkaebi
    dokkaebi.io/route-profile: hammer-no-k8s
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hammer-k8s-readonly
  namespace: dokkaebi-workers
  labels:
    app.kubernetes.io/name: dokkaebi-hammer
    app.kubernetes.io/part-of: dokkaebi
    dokkaebi.io/route-profile: hammer-k8s-readonly
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hammer-k8s-app-deployer
  namespace: dokkaebi-workers
  labels:
    app.kubernetes.io/name: dokkaebi-hammer
    app.kubernetes.io/part-of: dokkaebi
    dokkaebi.io/route-profile: hammer-k8s-app-deployer
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hammer-k8s-job-runner
  namespace: dokkaebi-workers
  labels:
    app.kubernetes.io/name: dokkaebi-hammer
    app.kubernetes.io/part-of: dokkaebi
    dokkaebi.io/route-profile: hammer-k8s-job-runner
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hammer-breakglass
  namespace: dokkaebi-workers
  labels:
    app.kubernetes.io/name: dokkaebi-hammer
    app.kubernetes.io/part-of: dokkaebi
    dokkaebi.io/route-profile: hammer-breakglass
    dokkaebi.io/activation: disabled
automountServiceAccountToken: false
